# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20171017_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='name',
            new_name='fname',
        ),
    ]
