# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20171031_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
