# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_details_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messreg',
            name='usn',
            field=models.CharField(max_length=15),
        ),
    ]
