# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20171101_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.PositiveIntegerField()),
                ('fdb', models.CharField(max_length=500)),
            ],
        ),
    ]
