# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messmenu', '0008_auto_20171101_1532'),
        ('student', '0007_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='messrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=15)),
                ('validity', models.DateField()),
                ('messbno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messmenu.mess')),
            ],
        ),
    ]
