# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guestreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('block', models.PositiveIntegerField()),
                ('meal', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
