# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messmenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food',
            field=models.CharField(max_length=500),
        ),
    ]
