# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messmenu', '0005_auto_20171029_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='s2',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
