# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messmenu', '0007_auto_20171029_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='mnu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.PositiveIntegerField()),
                ('s2', models.PositiveIntegerField()),
                ('weekday', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=15)),
                ('food', models.CharField(max_length=500)),
                ('messbno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messmenu.mess')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='messbno',
            field=models.PositiveIntegerField(),
        ),
    ]
