# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_messadmin_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messadmin',
            name='pwd',
            field=models.CharField(max_length=15),
        ),
    ]
