# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_auto_20171017_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messadmin',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
