# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_auto_20171031_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messadmin',
            old_name='name',
            new_name='fname',
        ),
    ]
